# Generated by Django 2.2.5 on 2019-12-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_data1'),
    ]

    operations = [
        migrations.CreateModel(
            name='data2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='data1',
            name='error',
        ),
    ]
