# Generated by Django 2.2.5 on 2019-12-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='more',
            name='age',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='more',
            name='city',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
